export const LANDING = '/'
export const REGISTER = '/register'
export const LOGIN = '/login'
export const VERIFY_EMAIL = '/verify-email'

export const USER_HOMEPAGE = '/user'
export const USER_ACCOUNT = '/user/account'
export const USER_POSTS = '/user/posts'
export const USER_CHALLENGES = '/user/challenges/'

export const ADMIN_DASHBOARD = '/user/admin'
export const ADMIN_CONTESTS_LIST = '/user/admin/contests'
export const ADMIN_CONTEST_DETAIL = '/user/admin/contests/'
export const ADMIN_USERS_LIST = '/user/admin/users'
export const ADMIN_USER_DETAIL = '/user/admin/users/'
export const ADMIN_CHALLENGES_LIST = '/user/admin/challenges'
export const ADMIN_CHALLENGE_DETAIL = '/user/admin/challenges/'
export const ADMIN_POSTS_LIST = '/user/admin/posts'
export const ADMIN_POST_DETAIL = '/user/admin/posts/'
