export const LANDING = '/'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const VERIFY_EMAIL = '/verify-email'
export const USER_HOME = '/user'
export const USER_ACCOUNT = '/user/account'
export const ADMIN = '/user/admin'
export const ADMIN_USER_LIST = '/user/admin/users'
